[build]
  command = "npm run build && npm run export"
  publish = "out"
  functions = "netlify/functions"

# Redirect API routes to Netlify Functions
[[redirects]]
  from = "/api/supabase-checkout"
  to = "/.netlify/functions/supabase-checkout"
  status = 200

[[redirects]]
  from = "/api/hero-images/*"
  to = "/.netlify/functions/hero-images/:splat"
  status = 200

[[redirects]]
  from = "/api/orders/*"
  to = "/.netlify/functions/orders/:splat"
  status = 200

[[redirects]]
  from = "/api/send-order-emails/*"
  to = "/.netlify/functions/send-order-emails/:splat"
  status = 200

[build.environment]
  # Disable secrets scanning to prevent build failures
  SECRETS_SCAN_ENABLED = "false"
  NODE_VERSION = "18.x"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_PRODUCTION = "false"
  # Ensure static export works
  NODE_ENV = "production"
  # Ensure environment variables are available during build
  NEXT_PUBLIC_SUPABASE_URL = "https://aizgswoelfdkhyosgvzu.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpemdzd29lbGZka2h5b3Nndnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNTUyMjUsImV4cCI6MjA3MDYzMTIyNX0.4a7Smvc_bueFLqZNvGk-AW0kD5dJusNwqaSAczJs0hU"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpemdzd29lbGZka2h5b3Nndnp1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTA1NTIyNSwiZXhwIjoyMDcwNjMxMjI1fQ.gLnsyAhR8VSjbe37LdEHuFBGNDufqC4jZ9X3UOSNuGc"
  # Email configuration
  RESEND_API_KEY = "re_6CyBkNKP_Ekzfh7Unk9GLM7n1WMFbwdoL"
  ADMIN_EMAIL = "dopetechnp@gmail.com"

# Environment variables for production (available to functions)
[context.production.environment]
  # Disable secrets scanning to prevent build failures
  SECRETS_SCAN_ENABLED = "false"
  NODE_ENV = "production"
  NEXT_PUBLIC_SUPABASE_URL = "https://aizgswoelfdkhyosgvzu.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpemdzd29lbGZka2h5b3Nndnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNTUyMjUsImV4cCI6MjA3MDYzMTIyNX0.4a7Smvc_bueFLqZNvGk-AW0kD5dJusNwqaSAczJs0hU"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpemdzd29lbGZka2h5b3Nndnp1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTA1NTIyNSwiZXhwIjoyMDcwNjMxMjI1fQ.gLnsyAhR8VSjbe37LdEHuFBGNDufqC4jZ9X3UOSNuGc"
  RESEND_API_KEY = "re_6CyBkNKP_Ekzfh7Unk9GLM7n1WMFbwdoL"
  ADMIN_EMAIL = "dopetechnp@gmail.com"

# Environment variables for all contexts (including functions)
[context.deploy-preview.environment]
  # Disable secrets scanning to prevent build failures
  SECRETS_SCAN_ENABLED = "false"
  NODE_ENV = "production"
  NEXT_PUBLIC_SUPABASE_URL = "https://aizgswoelfdkhyosgvzu.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpemdzd29lbGZka2h5b3Nndnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNTUyMjUsImV4cCI6MjA3MDYzMTIyNX0.4a7Smvc_bueFLqZNvGk-AW0kD5dJusNwqaSAczJs0hU"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpemdzd29lbGZka2h5b3Nndnp1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTA1NTIyNSwiZXhwIjoyMDcwNjMxMjI1fQ.gLnsyAhR8VSjbe37LdEHuFBGNDufqC4jZ9X3UOSNuGc"
  RESEND_API_KEY = "re_6CyBkNKP_Ekzfh7Unk9GLM7n1WMFbwdoL"
  ADMIN_EMAIL = "dopetechnp@gmail.com"

[context.branch-deploy.environment]
  # Disable secrets scanning to prevent build failures
  SECRETS_SCAN_ENABLED = "false"
  NODE_ENV = "production"
  NEXT_PUBLIC_SUPABASE_URL = "https://aizgswoelfdkhyosgvzu.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpemdzd29lbGZka2h5b3Nndnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNTUyMjUsImV4cCI6MjA3MDYzMTIyNX0.4a7Smvc_bueFLqZNvGk-AW0kD5dJusNwqaSAczJs0hU"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpemdzd29lbGZka2h5b3Nndnp1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTA1NTIyNSwiZXhwIjoyMDcwNjMxMjI1fQ.gLnsyAhR8VSjbe37LdEHuFBGNDufqC4jZ9X3UOSNuGc"
  RESEND_API_KEY = "re_6CyBkNKP_Ekzfh7Unk9GLM7n1WMFbwdoL"
  ADMIN_EMAIL = "dopetechnp@gmail.com"

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Static assets with proper MIME types
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Content-Type = "image/webp"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.avif"
  [headers.values]
    Content-Type = "image/avif"
    Cache-Control = "public, max-age=31536000, immutable"

# Product images
[[headers]]
  for = "/products/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Video files
[[headers]]
  for = "/video/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Logo files
[[headers]]
  for = "/logo/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Payment files
[[headers]]
  for = "/payment/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Manifest file
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=3600"

# Redirects for static assets
[[redirects]]
  from = "/payment/*"
  to = "/payment/:splat"
  status = 200
  force = true

# Critical redirects for Next.js
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

# Handle 404s for missing assets gracefully
[[redirects]]
  from = "/video/footervid.mp4"
  to = "/placeholder.jpg"
  status = 302
  force = true

[[redirects]]
  from = "/logo/dopelogo.svg"
  to = "/logo/simple-logo.svg"
  status = 302
  force = true

# Remove the problematic QR code redirect - let the actual QR code load
# [[redirects]]
#   from = "/payment/paymentQR.svg"
#   to = "/placeholder.jpg"
#   status = 302
#   force = true

# Handle all routes for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

